# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60, verbose_name=b'Pais')),
                ('state', models.CharField(max_length=60, verbose_name=b'Estado/Pronvicia')),
                ('area', models.CharField(max_length=60, verbose_name=b'Area')),
                ('street', models.CharField(max_length=60, verbose_name=b'Calle')),
                ('home', models.CharField(max_length=60, verbose_name=b'# Casa')),
                ('perimeter', models.IntegerField(verbose_name=b'Perimetro')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sheeps.Address')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('e_mail', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=15)),
                ('tellphone', models.CharField(max_length=15)),
            ],
            bases=('sheeps.address',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sheeps.Contact')),
                ('role', models.CharField(choices=[(b'1', b'Invitado'), (b'2', b'Miembro'), (b'3', b'Lider'), (b'4', b'Pastor/a'), (b'5', b'Pastor/a general')], max_length=80, verbose_name=b'Rol')),
                ('pic', models.FileField(upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('sheeps.contact',),
        ),
    ]
